version: '3.9'
services:
  postgres:
    image: postgres:15.5
    environment:
      POSTGRES_DB: "metrics"
      POSTGRES_USER: "metrics"
      POSTGRES_PASSWORD: "metrics"
      PGDATA: "/var/lib/postgresql/data/pgdata"
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      zookeeper:
          condition: service_started
#  producer:
#    image: petrov/producer:0.0.1-SNAPSHOT
#    ports:
#      - '8080:8080'
#    depends_on:
#      kafka:
#        condition: service_started
#  consumer:
#    image: petrov/consumer:0.0.1-SNAPSHOT
#    ports:
#      - '8081:8080'
#    depends_on:
#      postgres:
#        condition: service_started
#      kafka:
#        condition: service_started