spring:
  profiles:
    active: "dev"
---
spring:
  config:
    activate:
      on-profile: "dev"
  application:
    name: generator
generator:
  producerUrl: http://producer:8080/metrics
server:
  port: 8080
scheduler:
  fixedRate: 5000